### 1.3.1 Задание
Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и
единицами.

In [1]:
import numpy as np
arr = np.zeros(64).reshape(8, 8)

for i in range(8):
    for j in range(8):
        if i % 2 == 0:
            if j % 2 == 0:
                arr[i][j] = 1
        else:
            if j % 2 != 0:
                arr[i][j] = 1
print(arr)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


### 1.3.2 Задание
Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания
необходимо использовать функцию arrange.

In [2]:
arr = np.empty((0, 0))
for _ in range(5):
    arr = np.append(arr, np.arange(0, 5))
arr = arr.reshape(5, 5)
print(arr)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


### 1.3.3 Задание
Создать массив 3x3x3 со случайными значениями.

In [3]:
arr = np.random.random((3, 3, 3))
print(arr)

[[[0.2819309  0.57934572 0.24243441]
  [0.62766685 0.55985959 0.20118052]
  [0.68976026 0.69738923 0.09157349]]

 [[0.85183669 0.91964622 0.54706009]
  [0.11221861 0.77198449 0.80485347]
  [0.37617209 0.66941996 0.6825269 ]]

 [[0.1457155  0.2519944  0.87063789]
  [0.27702291 0.23359016 0.66730867]
  [0.33805841 0.40347092 0.31884173]]]


### 1.3.4 Задание
Создать матрицу с 0 внутри, и 1 на границах

In [19]:
arr = np.ones(10)

for _ in range(8):
    arr_promej = np.array([1])
    arr_promej = np.append(arr_promej, np.zeros(8))
    arr_promej = np.append(arr_promej, np.array([1]))
    arr = np.append(arr, arr_promej)
    
arr = np.append(arr, np.ones(10))
arr = np.reshape(arr, (10, 10))
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 1.3.5 Задание
Создайте массив и отсортируйте его по убыванию.

In [5]:
arr = np.random.random((10))
arr = np.sort(arr)[::-1]
print(arr)

[0.9819     0.92688754 0.77801896 0.70772041 0.68507492 0.5785664
 0.34600822 0.31309946 0.16119618 0.11017519]


### 1.3.6 Задание
Создайте матрицу, выведите ее форму, размер и размерность.

In [6]:
import random as r
arr = np.random.random((r.randint(1, 10), r.randint(1, 10)))
print(np.shape(arr), np.size(arr), np.ndim(arr))

(8, 7) 56 2


### Задание 2.3.1

In [7]:
import pandas as pd

a = pd.Series([20, 30])
b = pd.Series([30, 36])

Evk = ((b[0] - a[0])**2 + (b[1] - a[1]) ** 2)**0.5
print(Evk)

11.661903789690601


### Задание 2.3.2

In [8]:
frame = pd.read_csv('abolone.csv')
frame

Gender  Length  Diameter  Height  Whole weight  Shucked weight  \
0         M   0.455     0.365   0.095        0.5140          0.2245   
1         M   0.350     0.265   0.090        0.2255          0.0995   
2         F   0.530     0.420   0.135        0.6770          0.2565   
3         M   0.440     0.365   0.125        0.5160          0.2155   
4         I   0.330     0.255   0.080        0.2050          0.0895   
...     ...     ...       ...     ...           ...             ...   
4172      F   0.565     0.450   0.165        0.8870          0.3700   
4173      M   0.590     0.440   0.135        0.9660          0.4390   
4174      M   0.600     0.475   0.205        1.1760          0.5255   
4175      F   0.625     0.485   0.150        1.0945          0.5310   
4176      M   0.710     0.555   0.195        1.9485          0.9455   

      Viscera weight  Shell weight  Rings  
0             0.1010        0.1500     15  
1             0.0485        0.0700      7  
2             0.1415        0.2100      9  
3             0.1140        0.1550     10  
4             0.0395        0.0550      7  
...              ...           ...    ...  
4172          0.2390        0.2490     11  
4173          0.2145        0.2605     10  
4174          0.2875        0.3080      9  
4175          0.2610        0.2960     10  
4176          0.3765        0.4950     12  

[4177 rows x 9 columns]

### Задание 2.3.3

In [9]:
frame.head(2)

Gender  Length  Diameter  Height  Whole weight  Shucked weight  \
0      M   0.455     0.365   0.095        0.5140          0.2245   
1      M   0.350     0.265   0.090        0.2255          0.0995   

   Viscera weight  Shell weight  Rings  
0          0.1010          0.15     15  
1          0.0485          0.07      7

In [10]:
frame.tail(3)

Gender  Length  Diameter  Height  Whole weight  Shucked weight  \
4174      M   0.600     0.475   0.205        1.1760          0.5255   
4175      F   0.625     0.485   0.150        1.0945          0.5310   
4176      M   0.710     0.555   0.195        1.9485          0.9455   

      Viscera weight  Shell weight  Rings  
4174          0.2875         0.308      9  
4175          0.2610         0.296     10  
4176          0.3765         0.495     12

In [11]:
frame.shape

(4177, 9)

In [12]:
frame.describe()

Length     Diameter       Height  Whole weight  Shucked weight  \
count  4177.000000  4177.000000  4177.000000   4177.000000     4177.000000   
mean      0.523992     0.407881     0.139516      0.828742        0.359367   
std       0.120093     0.099240     0.041827      0.490389        0.221963   
min       0.075000     0.055000     0.000000      0.002000        0.001000   
25%       0.450000     0.350000     0.115000      0.441500        0.186000   
50%       0.545000     0.425000     0.140000      0.799500        0.336000   
75%       0.615000     0.480000     0.165000      1.153000        0.502000   
max       0.815000     0.650000     1.130000      2.825500        1.488000   

       Viscera weight  Shell weight        Rings  
count     4177.000000   4177.000000  4177.000000  
mean         0.180594      0.238831     9.933684  
std          0.109614      0.139203     3.224169  
min          0.000500      0.001500     1.000000  
25%          0.093500      0.130000     8.000000  
50%          0.171000      0.234000     9.000000  
75%          0.253000      0.329000    11.000000  
max          0.760000      1.005000    29.000000

In [13]:
frame.loc[1:4]

Gender  Length  Diameter  Height  Whole weight  Shucked weight  \
1      M    0.35     0.265   0.090        0.2255          0.0995   
2      F    0.53     0.420   0.135        0.6770          0.2565   
3      M    0.44     0.365   0.125        0.5160          0.2155   
4      I    0.33     0.255   0.080        0.2050          0.0895   

   Viscera weight  Shell weight  Rings  
1          0.0485         0.070      7  
2          0.1415         0.210      9  
3          0.1140         0.155     10  
4          0.0395         0.055      7

In [14]:
frame.iloc[1:4]

Gender  Length  Diameter  Height  Whole weight  Shucked weight  \
1      M    0.35     0.265   0.090        0.2255          0.0995   
2      F    0.53     0.420   0.135        0.6770          0.2565   
3      M    0.44     0.365   0.125        0.5160          0.2155   

   Viscera weight  Shell weight  Rings  
1          0.0485         0.070      7  
2          0.1415         0.210      9  
3          0.1140         0.155     10

In [15]:
new_frame = frame[frame['Diameter'] >= 0.62]
new_frame

Gender  Length  Diameter  Height  Whole weight  Shucked weight  \
1207      F   0.755     0.625   0.210        2.5050          1.1965   
1209      F   0.780     0.630   0.215        2.6570          1.4880   
1428      F   0.815     0.650   0.250        2.2550          0.8905   
1762      M   0.770     0.620   0.195        2.5155          1.1155   
1763      M   0.775     0.630   0.250        2.7795          1.3485   
2334      F   0.800     0.630   0.195        2.5260          0.9330   

      Viscera weight  Shell weight  Rings  
1207          0.5130        0.6785     11  
1209          0.4985        0.5860     11  
1428          0.4200        0.7975     14  
1762          0.6415        0.6420     12  
1763          0.7600        0.5780     12  
2334          0.5900        0.6200     23

### Задание 3.2.2

Загрузить фрейм данных по ссылке:
https://raw.githubusercontent.com/akmand/datasets/master/iris.csv.
Необходимо выполнить нормализацию первого числового признака
(sepal_length_cm) с использованием минимаксного преобразования, а
второго (sepal_width_cm) с задействованием z-масштабирования.

In [16]:
from sklearn import preprocessing
df = pd.read_csv('iris.csv')

length = list(df['sepal_length_cm'])
length = list(map(lambda x: [x], length))
length = np.array(length)

minmax = preprocessing.MinMaxScaler(feature_range = (0, 1))
minmax = minmax.fit_transform(length)
minmax


array([[0.22222222],
       [0.16666667],
       [0.11111111],
       [0.08333333],
       [0.19444444],
       [0.30555556],
       [0.08333333],
       [0.19444444],
       [0.02777778],
       [0.16666667],
       [0.30555556],
       [0.13888889],
       [0.13888889],
       [0.        ],
       [0.41666667],
       [0.38888889],
       [0.30555556],
       [0.22222222],
       [0.38888889],
       [0.22222222],
       [0.30555556],
       [0.22222222],
       [0.08333333],
       [0.22222222],
       [0.13888889],
       [0.19444444],
       [0.19444444],
       [0.25      ],
       [0.25      ],
       [0.11111111],
       [0.13888889],
       [0.30555556],
       [0.25      ],
       [0.33333333],
       [0.16666667],
       [0.19444444],
       [0.33333333],
       [0.16666667],
       [0.02777778],
       [0.22222222],
       [0.19444444],
       [0.05555556],
       [0.02777778],
       [0.19444444],
       [0.22222222],
       [0.13888889],
       [0.22222222],
       [0.083

In [17]:
width = list(df['sepal_width_cm'])
width = list(map(lambda x: [x], width))
width = np.array(width)

scaler = preprocessing.StandardScaler()
standard = scaler.fit_transform(width)
standard

array([[ 1.03205722],
       [-0.1249576 ],
       [ 0.33784833],
       [ 0.10644536],
       [ 1.26346019],
       [ 1.95766909],
       [ 0.80065426],
       [ 0.80065426],
       [-0.35636057],
       [ 0.10644536],
       [ 1.49486315],
       [ 0.80065426],
       [-0.1249576 ],
       [-0.1249576 ],
       [ 2.18907205],
       [ 3.11468391],
       [ 1.95766909],
       [ 1.03205722],
       [ 1.72626612],
       [ 1.72626612],
       [ 0.80065426],
       [ 1.49486315],
       [ 1.26346019],
       [ 0.56925129],
       [ 0.80065426],
       [-0.1249576 ],
       [ 0.80065426],
       [ 1.03205722],
       [ 0.80065426],
       [ 0.33784833],
       [ 0.10644536],
       [ 0.80065426],
       [ 2.42047502],
       [ 2.65187798],
       [ 0.10644536],
       [ 0.33784833],
       [ 1.03205722],
       [ 0.10644536],
       [-0.1249576 ],
       [ 0.80065426],
       [ 1.03205722],
       [-1.74477836],
       [ 0.33784833],
       [ 1.03205722],
       [ 1.72626612],
       [-0